apiVersion: v1
kind: Service
metadata:
  name: aisp-portal
  labels:
    app.kubernetes.io/name: aisp-portal
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: aisp-portal
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30015
