import { useMemo, useState } from "react";
import {
  AIPromptBar,
  AIResponseCard,
  AuditTrail,
  type AuditEntry,
  Badge,
  Button,
  type Citation,
  CitationChip,
  CitationSources,
  ConfidenceBadge,
  DisclaimerBar,
  HumanReviewBanner,
  Icon,
  RedactionToken,
  Section,
  type Source,
  SourceSelector,
  StatusDot,
  StreamingIndicator,
  Workspace,
} from "@aisp/components";
import {
  HANDOVER_CITATIONS,
  HANDOVER_NOTES,
  HANDOVER_OCCURRENCES,
  HANDOVER_RADIO,
  HANDOVER_SOURCES,
  HANDOVER_TASKS,
  type HandoverOccurrence,
  type ProvenanceTag,
  useBackend,
} from "../../backend";
import { BackingServicesPanel } from "../../portal/BackingServicesPanel";
import { MarkdownBody } from "../../portal/MarkdownBody";

/**
 * Shift Handover Summary — reference application use case (enhanced).
 *
 * The richer fixture exposes a full overnight shift: 5 occurrences,
 * 8 contemporaneous officer notes, 3 outstanding tasks, and a radio
 * log. The narrative is generated by the simulated LLM (or the real
 * one when the toggle is flipped) and grounded in those sources.
 */
export function ShiftHandoverUseCase() {
  const backend = useBackend();

  const sourcesForSelector: Source[] = useMemo(
    () =>
      HANDOVER_SOURCES.map((s) => ({
        id: s.id,
        label: s.label,
        icon: s.iconHint === "shield" ? "shield" : s.iconHint,
        description: s.description,
      })),
    [],
  );

  const [selectedSources, setSelectedSources] = useState<string[]>(
    HANDOVER_SOURCES.map((s) => s.id),
  );
  const [generating, setGenerating] = useState(false);
  const [draft, setDraft] = useState<{
    text: string;
    confidence: "high" | "medium" | "low";
    citationIdxs: number[];
    timestamp: Date;
  } | null>(null);
  const [openOccurrenceId, setOpenOccurrenceId] = useState<string | null>(null);

  const [audit, setAudit] = useState<AuditEntry[]>([
    {
      id: "0",
      timestamp: new Date(),
      actor: "Officer J. Brand",
      action: `Opened Shift Handover Summary — ${HANDOVER_OCCURRENCES.length} occurrences attended`,
    },
  ]);

  function log(action: string, ai = false) {
    setAudit((prev) => [
      ...prev,
      {
        id: String(prev.length),
        timestamp: new Date(),
        actor: ai ? "AISP" : "Officer J. Brand",
        action,
        ai,
      },
    ]);
  }
  function logProv(label: string, p: ProvenanceTag) {
    log(`${label} via ${p.mode}/${p.source} (${p.latencyMs}ms)`, true);
  }

  function toggleSource(id: string) {
    setSelectedSources((prev) =>
      prev.includes(id) ? prev.filter((s) => s !== id) : [...prev, id],
    );
    log(`Toggled source ${id}`);
  }

  async function handlePrompt(prompt: string) {
    log(`Submitted prompt (${prompt.length} chars, ${selectedSources.length} sources in scope)`);
    setGenerating(true);
    setDraft(null);
    try {
      const r = await backend.inference.complete({
        useCaseId: "shift-handover",
        prompt: prompt + ` [scope: ${selectedSources.join(",")}]`,
        context: HANDOVER_OCCURRENCES.filter((o) => selectedSources.includes(o.id)).map((o) => ({
          id: o.id,
          title: `${o.occNumber} — ${o.type}`,
          snippet: o.summary,
        })),
      });
      setDraft({
        text: r.data.text,
        confidence: r.data.confidence,
        citationIdxs: r.data.citations,
        timestamp: new Date(),
      });
      logProv(`Generated handover narrative (${r.data.text.length} chars)`, r.provenance);
    } catch (e) {
      log(`Generation failed: ${(e as Error).message}`);
    } finally {
      setGenerating(false);
    }
  }

  const draftCitations: Citation[] = useMemo(() => {
    if (!draft) return [];
    const seen = new Set<number>();
    const list: Citation[] = [];
    for (const ci of draft.citationIdxs) {
      if (seen.has(ci)) continue;
      seen.add(ci);
      const found = HANDOVER_CITATIONS.find((c) => c.index === ci);
      if (!found) continue;
      list.push({
        index: list.length + 1,
        title: found.title,
        meta: found.meta,
      });
    }
    return list;
  }, [draft]);

  function accept() {
    log("Accepted handover draft — posted to shift log");
    setDraft(null);
  }
  function reject() {
    log("Rejected handover draft");
    setDraft(null);
  }

  const openCount = HANDOVER_OCCURRENCES.filter((o) => o.status === "open").length;
  const closedCount = HANDOVER_OCCURRENCES.length - openCount;

  return (
    <Workspace>
      <DisclaimerBar />

      <Section
        title="Shift overview"
        meta={
          <span style={{ display: "flex", gap: 6 }}>
            <Badge variant="warning">{openCount} open</Badge>
            <Badge variant="ok">{closedCount} cleared</Badge>
            <Badge>{HANDOVER_TASKS.length} tasks</Badge>
          </span>
        }
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
            gap: 10,
          }}
        >
          <Stat label="Officer" value="Cst. J. Brand" helper="Badge 5821 — Unit 14" />
          <Stat label="Shift" value="02:00 – 06:40" helper="2026-04-12 (Sat)" />
          <Stat label="Occurrences" value={String(HANDOVER_OCCURRENCES.length)} helper={`${openCount} open / ${closedCount} closed`} />
          <Stat label="Notes" value={String(HANDOVER_NOTES.length)} helper="Contemporaneous entries" />
          <Stat label="Radio events" value={String(HANDOVER_RADIO.length)} helper="Logged Pri-1 / Pri-2 / Tac-3" />
        </div>
      </Section>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 320px",
          gap: 14,
          alignItems: "start",
        }}
      >
        <div style={{ minWidth: 0 }}>
          <Section title="Compose handover">
            <AIPromptBar
              placeholder="E.g. 'Draft a handover prioritising open occurrences; preserve subject anonymity.'"
              onSubmit={handlePrompt}
              busy={generating}
            />
          </Section>

          {generating && (
            <Section title="Working">
              <StreamingIndicator label="Drafting handover" />
            </Section>
          )}

          {draft && (
            <>
              <HumanReviewBanner
                title="Officer review required"
                body="This handover draft was generated by AI and must be reviewed before it is posted to the shift log."
                onAccept={accept}
                onReject={reject}
                onEdit={() => log("Opened handover draft for editing")}
              />
              <AIResponseCard
                role="ai"
                model="AISP · Shift Handover"
                confidence={draft.confidence}
                timestamp={draft.timestamp}
                actions={
                  <Button
                    variant="ghost"
                    size="sm"
                    leadingIcon={<Icon name="copy" size={14} />}
                    onClick={() => log("Copied draft to clipboard")}
                  >
                    Copy
                  </Button>
                }
              >
                <MarkdownBody>{draft.text}</MarkdownBody>
                {draftCitations.length > 0 && (
                  <p>
                    {draftCitations
                      .filter((c) => draft.citationIdxs.includes(c.index))
                      .slice(0, 4)
                      .map((c) => (
                        <CitationChip key={c.index} citation={c} />
                      ))}
                  </p>
                )}
              </AIResponseCard>

              {draftCitations.length > 0 && (
                <Section title="Sources" count={draftCitations.length}>
                  <CitationSources citations={draftCitations} />
                </Section>
              )}
            </>
          )}

          <Section
            title="Occurrences attended"
            count={HANDOVER_OCCURRENCES.length}
          >
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: 4,
              }}
            >
              {HANDOVER_OCCURRENCES.map((o) => (
                <OccurrenceRow
                  key={o.id}
                  occ={o}
                  open={openOccurrenceId === o.id}
                  onToggle={() => {
                    setOpenOccurrenceId((prev) => (prev === o.id ? null : o.id));
                    log(`Opened occurrence ${o.occNumber}`);
                  }}
                  onRedactionReveal={(cat) =>
                    log(`Revealed ${cat} on occurrence ${o.occNumber}`)
                  }
                />
              ))}
            </div>
          </Section>

          <Section title="Outstanding tasks" count={HANDOVER_TASKS.length}>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {HANDOVER_TASKS.map((t) => (
                <div
                  key={t.id}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "20px 1fr 90px",
                    gap: 8,
                    alignItems: "center",
                    padding: "6px 8px",
                    border: "1px solid var(--aisp-border-soft)",
                    background: "#ffffff",
                  }}
                >
                  <StatusDot
                    variant={
                      t.priority === "high"
                        ? "error"
                        : t.priority === "medium"
                          ? "warning"
                          : "muted"
                    }
                  />
                  <div>
                    <div style={{ fontWeight: 600, fontSize: "var(--font-size-sm)" }}>
                      {t.title}
                    </div>
                    <div
                      style={{
                        fontSize: "var(--font-size-xs)",
                        color: "var(--aisp-text-muted)",
                      }}
                    >
                      {t.detail}
                    </div>
                  </div>
                  <div
                    style={{
                      fontSize: "var(--font-size-xs)",
                      color: "var(--aisp-text-muted)",
                      textAlign: "right",
                    }}
                  >
                    Due {t.due}
                    <br />
                    <Badge
                      variant={
                        t.priority === "high"
                          ? "error"
                          : t.priority === "medium"
                            ? "warning"
                            : "default"
                      }
                    >
                      {t.priority}
                    </Badge>
                  </div>
                </div>
              ))}
            </div>
          </Section>

          <Section title="Radio communications" count={HANDOVER_RADIO.length}>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: 4,
                fontSize: "var(--font-size-sm)",
                fontFamily: "var(--font-mono)",
              }}
            >
              {HANDOVER_RADIO.map((r) => (
                <div
                  key={r.id}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "60px 70px 1fr",
                    gap: 8,
                    padding: "3px 0",
                    borderBottom: "1px solid var(--aisp-border-soft)",
                  }}
                >
                  <span style={{ color: "var(--aisp-text-muted)" }}>{r.at}</span>
                  <Badge variant={r.channel === "Tac-3" ? "ai" : "blue"}>{r.channel}</Badge>
                  <span>{r.text}</span>
                </div>
              ))}
            </div>
          </Section>
        </div>

        <aside style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <BackingServicesPanel
            services={[
              { kind: "llm", name: "llama-3.1-70b", detail: "narrative drafting" },
              { kind: "relational", name: "occurrences", detail: "shift-scoped query" },
              { kind: "object", name: "radio-log/", detail: "Pri-1 / Pri-2 / Tac-3" },
            ]}
          />
          <SourceSelector
            sources={sourcesForSelector}
            selectedIds={selectedSources}
            onToggle={toggleSource}
          />

          <Section title="Officer notes" count={HANDOVER_NOTES.length}>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: 4,
                fontSize: "var(--font-size-sm)",
                maxHeight: 240,
                overflowY: "auto",
              }}
            >
              {HANDOVER_NOTES.map((n) => (
                <div
                  key={n.id}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "44px 1fr",
                    gap: 6,
                    padding: "3px 0",
                    borderBottom: "1px solid var(--aisp-border-soft)",
                  }}
                >
                  <span
                    style={{
                      fontFamily: "var(--font-mono)",
                      fontSize: "var(--font-size-xs)",
                      color: "var(--aisp-text-muted)",
                    }}
                  >
                    {n.at}
                  </span>
                  <span>{n.text}</span>
                </div>
              ))}
            </div>
          </Section>

          <Section title="Output options">
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: 6,
                fontSize: "var(--font-size-sm)",
              }}
            >
              <label style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <input type="checkbox" defaultChecked /> Third-person voice
              </label>
              <label style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <input type="checkbox" defaultChecked /> Redact victim PII
              </label>
              <label style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <input type="checkbox" defaultChecked /> Group by status (open/closed)
              </label>
              <label style={{ display: "flex", gap: 6, alignItems: "center" }}>
                <input type="checkbox" /> Include speculative leads
              </label>
              <div
                style={{
                  marginTop: 6,
                  fontSize: "var(--font-size-xs)",
                  color: "var(--aisp-text-muted)",
                }}
              >
                Trust: <ConfidenceBadge level={draft?.confidence ?? "medium"} />
              </div>
            </div>
          </Section>

          <AuditTrail entries={audit} />
        </aside>
      </div>
    </Workspace>
  );
}

function Stat({
  label,
  value,
  helper,
}: {
  label: string;
  value: string;
  helper?: string;
}) {
  return (
    <div
      style={{
        padding: 10,
        border: "1px solid var(--aisp-border)",
        background: "#ffffff",
      }}
    >
      <div
        style={{
          fontSize: "var(--font-size-xs)",
          color: "var(--aisp-text-muted)",
          textTransform: "uppercase",
          letterSpacing: "0.04em",
        }}
      >
        {label}
      </div>
      <div style={{ fontSize: "var(--font-size-lg)", fontWeight: 600 }}>{value}</div>
      {helper && (
        <div
          style={{
            fontSize: "var(--font-size-xs)",
            color: "var(--aisp-text-muted)",
          }}
        >
          {helper}
        </div>
      )}
    </div>
  );
}

function OccurrenceRow({
  occ,
  open,
  onToggle,
  onRedactionReveal,
}: {
  occ: HandoverOccurrence;
  open: boolean;
  onToggle: () => void;
  onRedactionReveal: (cat: string) => void;
}) {
  return (
    <div
      style={{
        border: "1px solid var(--aisp-border-soft)",
        background: "#ffffff",
      }}
    >
      <button
        type="button"
        onClick={onToggle}
        style={{
          width: "100%",
          textAlign: "left",
          background: "none",
          border: 0,
          padding: "8px 10px",
          font: "inherit",
          color: "inherit",
          cursor: "pointer",
          display: "grid",
          gridTemplateColumns: "20px 90px 1fr 80px 90px",
          gap: 8,
          alignItems: "center",
        }}
      >
        <Icon name={open ? "chevron-down" : "chevron-right"} size={12} />
        <span style={{ fontFamily: "var(--font-mono)", fontSize: "var(--font-size-sm)" }}>
          {occ.occNumber}
        </span>
        <span>{occ.type}</span>
        <span style={{ fontSize: "var(--font-size-xs)", color: "var(--aisp-text-muted)" }}>
          {occ.attended}
          {occ.cleared ? ` → ${occ.cleared}` : ""}
        </span>
        <Badge variant={occ.status === "open" ? "warning" : "ok"}>{occ.status}</Badge>
      </button>
      {open && (
        <div
          style={{
            padding: "0 12px 10px 38px",
            fontSize: "var(--font-size-sm)",
            display: "flex",
            flexDirection: "column",
            gap: 6,
          }}
        >
          <div>{occ.summary}</div>
          <div>
            <strong>Location: </strong>
            {occ.location}
          </div>
          <div>
            <strong>Parties: </strong>
            {occ.parties.map((p, i) => (
              <span key={i}>
                {p.role}:{" "}
                {p.redact && p.name ? (
                  <RedactionToken
                    category={p.redact}
                    value={p.name}
                    revealable
                    onReveal={() => onRedactionReveal(p.redact!)}
                  />
                ) : (
                  p.name ?? "—"
                )}
                {i < occ.parties.length - 1 ? "; " : ""}
              </span>
            ))}
          </div>
          {occ.followUps.length > 0 && (
            <div>
              <strong>Follow-ups:</strong>
              <ul style={{ margin: "4px 0 0 18px", padding: 0 }}>
                {occ.followUps.map((f, i) => (
                  <li key={i}>{f}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default ShiftHandoverUseCase;
